"""
"""

from busylight.lights import Light, HIDLight, SerialLight

ABSTRACT_LIGHT_SUBCLASSES = [Light, HIDLight, SerialLight]
CONCRETE_LIGHT_SUBCLASSES = Light.subclasses()
ALL_LIGHT_SUBCLASSES = ABSTRACT_LIGHT_SUBCLASSES + CONCRETE_LIGHT_SUBCLASSES

BOGUS_DEVICE_ID = (0xFFFF, 0xFFFF)
