""" """

import typer
from busylight_core import Light
from loguru import logger

udev_rules_cli = typer.Typer(help="Generate udev rules for supported lights.")


@udev_rules_cli.command(name="udev-rules")
def generate_udev_rules(
    output: typer.FileTextWrite = typer.Option("-", "--output", "-o"),
) -> None:
    """Generate Linux udev rules for all supported lights.

    The rule file generated by this subcommand includes rules for all
    known supported devices. By default, these device file permissions
    are set to 0666 (ugw=rw-) when detected by the udev subsystem.
    Users are encouraged to tailor these rules to suit their security
    needs.
    """
    logger.info(f"generating udev rules: {output}")

    try:
        rules = Light.udev_rules()
        about = [
            "# Generated by `busylight udev-rules` https://github.com/JnyJny/busylight",
            "#",
        ]

        print("\n".join(about), file=output)

        for device, rules in rules.items():
            print("\n".join(rules), file=output)

    except Exception as error:
        typer.secho(f"Error generating udev rules: {error}", fg="red")
        raise typer.Exit(code=1)
