name: Auto-merge on LGTM

on:
  issue_comment:
    types: [created]

jobs:
  auto-merge:
    if: |
      github.event.issue.pull_request &&
      contains(github.event.comment.body, 'LGTM') &&
      github.event.comment.user.login == 'JnyJny'
    runs-on: ubuntu-latest
    steps:
      - name: Enable auto-merge
        run: gh pr merge ${{ github.event.issue.number }} --repo ${{ github.repository }} --squash --auto
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
