name: Linux

on:
  push:
    tags:
      - "*"
  workflow_dispatch:
      
jobs:
  test-on-linux:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.8', '3.9', '3.10', '3.11']
    name: Test BusyLight For Humans ${{ matrix.python-version }} on Linux
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install libusb
        run: |
            sudo apt-get update
            sudo apt-get install -y libusb-1.0-0-dev libudev-dev
      - name: Install pip/poetry/pytest
        run: |
            python -m pip install --upgrade pip
            pip install poetry pytest
      - name: Install Busylight-For-Humans with WebAPI
        run: |
            poetry install -E webapi
      - name: Test with pytest
        run: |
            poetry run pytest          
            
