name: Release

on:
  workflow_run:
    workflows: ["Test On All Platforms"]
    types:
      - completed
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    name: Build and Publish
    if: |
      github.event.workflow_run.conclusion == 'success' &&
      startsWith(github.event.workflow_run.head_branch, 'refs/tags/v') &&
      !endsWith(github.event.workflow_run.head_branch, '-test')
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/project/busylight-for-humans

    steps:
      - uses: actions/checkout@v4

      - name: Install uv and set Python version.
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.7.5"
          python-version: 3.9

      - name: Build package.
        run: |
          uv build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
